[package]
name = "acme-validator-dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acme2 = "0.5"
openssl = "0.10.38"
futures = "0.3.17"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
color-eyre = "0.5"
eyre = "*"
tokio = {version = "1.14.0",features = ["macros","rt-multi-thread"]}
reqwest = "0.11.6"
serde = {version = "1.0.130", features=["derive"]}
base64 = "0.13"
toml = "0.5.8"
structopt = "0.3.25"