[package]
edition = "2021"
name = "acme-dns-online"
version = "0.1.0"
[dependencies]
acme2 = "0.5"
base64 = "0.13"
color-eyre = "0.5"
eyre = "*"
futures = "0.3.17"
openssl = "0.10.38"
reqwest = "0.11.6"
sha2 = "0.9.8"
structopt = "0.3.25"
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
trust-dns-proto = "0.20.3"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "fs"]
version = "1.14.0"
