# Address for the DNS server to listen on.
# The port is should probably be 53.
dns_listen_adr = "1.2.3.4:53"

# A first account
# accounts are identified by
# their email and their private key
[[accounts]]
email= "contact@doma.in"
private_key_path = "priv_key.pem"

# The certificates ordered for that account.
[[accounts.certificates]]
domains =  ["doma.in","*.doma.in"]
output_file = "fullchain.pem"

# A second account
[[accounts]]
email = "contact@foo.tld"
private_key_path = "priv_key_2.pem"

[[accounts.certificates]]
domains = ["foo.tld","subdomain.foo.tld"]
output_file = "fullchain2.pem"