# your LSE account email address
email= "account@email-provider.com"

# The domain managed by online/dedibox.
# A single certficate valid for
# `doma.in` and `*.doma.in` will be requested
domain =  "doma.in"

# The RSA private key that identify your LSE account
# in PEM format, encoded in base 64.
# To generate one:
# `openssl genrsa 2048 | base64 -w0`
# or
# `openssl genrsa 4096 | base64 -w0`
private_key = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdHI5TzNDODlLTDBWbHB4NFJOK2wxMEw4b01WSXo1VjBWM3lGT0xvSmFCTFBya0Z5CkVSN3VNb2hvdEh0SGlTUnNwVGJMTkhNQVM1Ukk0K1pNNG1nQ1hjYWxZU1psditoNlp2TFFwVVVTZmpBMkUwZUwKSXFndnRVS2hJdVdVbXgvTld4aC9IdEZ3SjRtcEdTQnV0N0srTzE4a24ySjM4MjFIdFlPTStyc1gzOTFFTTdUUAo1UXNRMGVoY2o4bFgyaHRMOXlBUjU0bGhWZXdFUndwTmxSOURnYlhTR2xwSUdTdE1ja2JwSWl4V2ZoMnYvU1V4CnlQSUpZS3RnbW56STdBcG0reTNoaE9tR3RZTkJva3h6OXFoSm1LcjRveWlhTm9FeUZwUVY4ZnN4M01ITXhNS0MKNTZyODVoeFFxTVNiZDFkSWtncjdRc3JzeG9tQjh4b1lsZEtOSVFJREFRQUJBb0lCQUVNTjJUTERobzVmS3YregpkQkhaZWpHTkc4TW1BSHhpbTJqS2dOdDZyNTduWUJyUldyaGJnQTA4cmlhaklYRjUwditnSmxtZFpOdFdrcFJFCjJhc3RmTWpKN2I3QzV3ek9rYk1hbjJJMUFQOGFVNDBwY0MwTVIwMGNJS0g4V1ZXK0NvekZaVWQ2azh0K0lIVGUKeUtGUXphcGRVOFBEenIyY09IYXF5VnpxcjJ6dFZRSjczalJBV28vbmRVUVdPRUl6bkpCam1ObDhGV3RiNDlPcgpjQ1IyUzd2UGlCUzh1NWZmZlpkTE90L3d1bzlZdCtWZ2IxQ0dheDRzM2JaY1E5U0RYbHRBb2tQYmtXOWdKbm9tCnE5bEVYWnhPVHlZUmNTQis5VzcxaDlqUktrYlZKN1p3L2hVdFB3MXhjMlFFUHdBQkdRZ0tpWTlDcWdhOUFSK0wKaXFoQ3RqMENnWUVBN1ZKWDRJdWdsSkhxUWxnZFovaWhobnlLWlFGUkFvbzQ2NlR0VEIxNURhMkx2bDBZT25hcgorWVdSUGZrdm5ZTktDQjhlNDlOUDR5ZUJkcTlEbVdkYnZqRm9ZU2xiRG1hNTdzTThlbVJIQ0JMVG90SG5kSHJCClR2MDd2MzR2RjN2KzZvWjNwTFJzMnRhUXlTb2hUTyswbVAyaWJScXdINkxJc2J5OHJuOU8wRWNDZ1lFQXhTRmcKck1wVWlTRHdRdE5ScUNVT2hHd1lFQlhray96M0ZCVGZWaVV4VnFDZFR3QnZZK21rZVE5dGRNcEQwaGVzaWxodApQZ015OG1kZDQwaTUwU2YzT1Axa3BwL0cxaUZFOGN5dnBzcGlvV3lCUlFPbitTajJ6MFJIc0pERHNSeTFabjF2Cm1lSlhkUDYxYVdUYmpHYVJpN09yVEZYeGRlZE9UdkhxZFcySGsxY0NnWUFSbDNzQUlCbUZLZFBObXk2QzJJRlEKc01hcGVoR0JPTEhEZGZSSkloNHBEMlkrZERRcGtVWnFOcVp2aTVzbDkrZHk5cXVaZzc1MlBpVndvTWxJQTh0ZgpLOVpxN1YvY2oyelU4QS81bXBsUlZlUHVPOVVHWTFzVStkeUY4MXFXU1JDNlhjRmNxaXN2aFp3eDdUZU90bTRTCnNTcHJJQUZTTndUZGQvb2NqVDlRWFFLQmdEb05qazdVZHZpN1BvWXZmVWlyUVE4MlZnL0dvcjRDTFRFNHhGeTIKTDBWM24xdjRvTlVucFV3Umd3WjEybXN3bFp0WVZ6Ti85YXoxUyt6M0tlR3loMWU5SjdyNktyQThzL1VSZGxrRQpHTys0NklqT2Z0VWRmekdpeGduMVYrdjhyRjgyYVh0RDhNVi9qU1V3a29kU1hXSnEwdk4wQzl2UTluckJPMjdCCmhyK1pBb0dBUDBnSHNoQ3RNY3ZLY2lscE9sbk0xRWxiZHRSZXNHVE1TL0xwR0hlTVc3NnJkOHpsamp1WVk2VTcKb1lKUkJXYytqS1FLSVRiYWVjOEdPYmlRWHNyOUpFeGEzUTI0ZTZPTkxHUU1VWC9CT2ViVGFuUjB5eHVlTng2OApxKzFlUkdVRm4yaHRHUDQrNnp0K0prNDd1Ym9iQ2srYlFkamVaQnkvMFRJb3dhZm5DR3c9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="

# Your online API token
online_token = "546af653eca8d727ccf4adbc57fd6d213d7129d7"

# Output file to store the full chain
# in PEM format
output_file = "fullchain.pem"

# Whether to use LSE staging server
# in production, set this to false.
# Defaults to true
# staging = false