# your LSE account email address
email= "account@email-provider.com"

# The domain managed by online/dedibox.
# A single certficate valid for
# `doma.in` and `*.doma.in` will be requested
domain =  "doma.in"

# Your online API token
online_token = "546af653eca8d727ccf4adbc57fd6d213d7129d7"

# Output file to store the full chain
# in PEM format
output_file = "fullchain.pem"

# Whether to use LSE staging server
# in production, set this to false.
# Defaults to true
# staging = false

# The RSA private key that identify your LSE account
# in PEM format, encoded in base 64.
# To generate one:
# `openssl genrsa 2048 | base64`
# or
# `openssl genrsa 4096 | base64`
private_key = """
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS2dJQkFBS0NBZ0VBK1cxeS9uY29x
M3BWMVltWHhON0c1dWxhM1kxaFk0aTdqNmJOODRpNmd2bjJlZ1Q2CkhvWTlHY250d3F2cUcwVTNB
dXQvdEpjWGRUV1F2R3REZ0NoQzdwUldmVlJJQlV3NHc4ZHZPekQ0N0FmYWdqaEgKL0V3bGhWc1JM
R0p6TGZGYzFmd2VoOSt6c0lHWVE5QncxSGJsMTIwcHNSUmlaV3BJV1BaK1plUXBDSjBmNUNrNwpO
aW1wQXJBZEtIQVpFTitLUWtLeUp5YUkyODVEYmQ5TEVUeWV0eVRIdmxaSnZ3VlV3bzNsRnR6YUhh
ZkRrY2l3ClhqR3prMVZhZU5XaklCbE1nMXh2anFJdC9JVEdJRGNmSHdZL0QvbEJBdGdOSnhUZTZK
RTRkWUtzYzl3UEhLWnAKOHdkMzVOSkN6MFQ3ZCtSQ1hScVQyek9pbjlXb1dkMWo1aE9DZ0xXU05r
V3VhS1p1VDJFS01ueTJjcWpmNEY1cgpEcDZSMVpManoyYWgyUGExaWFXZW9XVmZQMzVrNGsyRzBo
Ums4OU50aVdTUlJMTUZwRE85L1Q1RDhtQzZrUDYvCnBTUEtjVktDR0ZXclZWM2xtVVduMW50NEJB
WmhSR2ZTbW82ZlZSeTlLKzQraGdNQVR6aTIrNFVlR25vanFZRmoKVU1ETlhsY1lQZ2tPYVA2L0Fi
ZXpyYzdINEk2MDllbHd2eitCWnJ4ODMrQWVhek0rTEgwb29YeVNPOGQ5c1k2YwpWM1JseU14cDQx
bXRqUXlwQlRQV2RoR2I1d3g0ZVFYalg4aXM5bnpOTEZiNjVHZUlXN3F3YzJKTStrL1RsWVlmCmVq
dnhVM3VabldZMExHdkhORlVaN2lBRnhzRk5rKzB2bExqY2dHSmhjNHFBN1R2QllWemVCeW5CaUxF
Q0F3RUEKQVFLQ0FnRUExSVdORllReUF1bVplUGhqZURyWS9xYVY1WEF4S3IyMkVnL3VLekswdUNT
Qy9qUi9hTUs0RE9FZwoxRjNtZXBYZTZYMytzY0NMSERNbnYyTWxnR3pObXJxSmR2LzQzWXEwVXh2
NmlsU1B3NHh0Z2NheWp5WFNVbTNsCmxBdk9WN2J2Z3VQdW41YmJZK2tIODhBR1l3RnJsTUpPWTdN
YW80NkxWa0d3TU9EV2xhQkxLL3gxbHhDb0VNSSsKRmRadGhSTHltc0o1U1NKc09kemxWeGlLdllV
Sk5zTC83ZzFYaUlyaVRXTFpiMEYrRndaNmZCeWpLWjd2Z3ZtVwp2SjVLLzI2TzR0NC9yeWhBUm9o
YXg5Z3ZqQittVzlYa3JxZW5qVVViS00yVGJZeUpvNjQ4c2d5WStabkRiaFE1CkdLR09JZms3RWxr
eTRmSjgvZkx1SHFPa0dzVkV5dmROQ2VldXdFZ3hKVkUzZnpyRlJhNWVFOTk1Q3lCaG0wNDcKdTJt
Ri9SdXhQY256Z1BuUkVxQlo2anpYNjFOWWdyeS9aY2w2d2g4c284N0ljMVBPWHl1SkdyS2ZBcGND
VWJaeApjRUZjdjBmb2prYlVvZlArZEIyRjlZUmRiRWNqWTc5K0xIL2V0VHE1b2twMWRsQXBhbk5v
TFRwMG1IVmhwdFE4CklHQi9TNVkyLzBHUnRvaEJVelBTOFBUWWtpbkgzSVF5TUllbW8xSXZDVVFW
MDlsd1BkQm1MSjJpcExHRXNtS2EKak1LSW9oZFZTR20zWmFudytaSEp6SWt3Qkpwc1plNzRQVGp1
SFdVMVdQL2RHRncyTDlWV3BBUG1LQUpYdmorOQpUK0lBS1NDMno0UGthZGI0VjRpb0NucjJwRmhq
QUM3L0wzMXpIaXMzVDdYOHFDYThnQUVDZ2dFQkFQMFlyNzBtCnNGd1FLY2xmYkM1RmNDM09YQTBk
eXBla28yVTQ0VTZFT3VJTHZFdjF6djFZOXZUVWFDLzhVVDNjb2praU9CS1QKYmhKNHBZVWdiZjBT
aDdmQWpFa0hTT01tZnlnT28zU25ya3EvNWFOMDNrUVJyRlFxZjJXKzNLSzVrTktWWWNHcwpWdUsy
eXdBNVJnUHdyOEZKa2c0My9OMm40OG43NGtWZ1Bta3V4QnNDNTlFcWhXQUZCd2kxYUVzTnBjNWZC
YUtVClYyTDhBYWJ3SzVqNmorcldkTmNHRTRqQVFvTVZFVlNVY2VOK3dLSlhKQ1l3VHh4VkJSRnRk
bzY2U0FITnRrYmoKUE9BMTdKUTZUWmNaWUptOUpPbEdHa0lobDJKMWYzQ3N4aS9CNE1CcXovSEcv
bWVTa01ocHpJcGcyVTVLWDJBegpLZ3dCK2tpNlpLOXZLMEVDZ2dFQkFQeEovTlJEZHpIdlVwNjVP
UmV6SytoK053UHQyK1dROER3N2lXNDVtNVE3CkVlSXBsQ1IxSXB1Tk0zSXVDckJmSStGS0llVFhN
NnAxZ2lhUVdMS1dqbFpZQnhPajN3TW1DSCtHZjFzRFd6VUEKQ3lWWEJNc2hOUmVkT3A0N0lSS3ox
bEkzSTRhK1B0cUl3bzB0ZFRqYWFCaVFsdXloN05yUHJIb3NHNnQ1dk1BWQprK2liR09nV0hYZ29n
S3F6WXE0MU9uNUNsSlYwd1VCblRmVlRmYjI1VG80QVRQdmhxVE45S2E2bEpPdnAySTZUCjVZSVlI
YS9CR3pucVpIYkFGSnBtM3NTQllzUU1HK3gyWXBWRTQvUTJWU1d6VEVGQ050d0lFUlJSOXNyRHBO
K1kKMWxHeC9URjJkc2NzbnU0eGQyek1oV2FLaXQxckg1NUR3UEtpUCtCb01YRUNnZ0VBQ3VFQnhN
Nmg3QU1oMks4SwpWbDdUdUpSVExwa21PU2h4Z1l0VlcrdWhJRkJDMHIwSkhhaXlUTW5JaEsrQ3lu
YnVYaWhUWXJFRm5UT2tZYm1JCklNV29JY1RjQXRPV1ZYVTFLQUtoRWdXWEgwMXFVSUZZZ0hLR0Jz
UWczNzI1ZkNFZjBYMXNTMGZlSURhZE9UQTkKQ3pSUVNhMmc0bzJUaCsrTWdnVWFyOEs0VEFzZmtN
MnFLenA1cXl2c0pucXR0ZlFyT1ZpcVJGZTkvZG81TS9URQoydm1DTUNUeHRzQmpISkN2Q3pWZm5s
UVhKU0V3cEltOFd3dmVpcWc0NUl2ZytiZVdHc1c5M1FRdGZMRzBycFptCitXUzAyMGJmREV2Z0d4
R1lrVG5kdFhrbnQ2dk12bGlaQVpwOUd2U1kxcFI5bjBFVWRpSUtRWGRSaWx5WFpvTGsKaXduclFR
S0NBUUVBNUhxOUZoN2pXNzI1dlRWUmx6MFVqc0YvWVhlUXBoN1U4amVaQnRIMUxCRXk2UGR1eW5X
cQptZVVPcW1FNEhQS010QU5ISHRBbVlrRjVWU04wc0lmWThDbFlmMWp4SnhEU3NXdEUrMC9XMGZE
d0p5amZsbmJFCmRsWldOK2FrMVNNNC9jd2h5RzJTenFiOFNvN1lrbHg1MllWWXFZVWIxQzR2clpV
MG1kN3VLYW9ZaVplc3ZzTUkKZlVGeEJTYmdQNVRGSElOL3ZMcTRLWE5sRHNCR0tBUWlPRWZkY0Yr
MXRJT3R0QlNyazF0OFcrTmsvcVNJZmhzTQpaUzc1UFBKSHRtMWpZZU1yWnhEd1dQMzkyZUZCOEhF
a083aGRYdHh3Z21ScjAxTkhoZW9ZN3NhamtlajN2RXZrCjFneDdBb3laODFabG1hL3Vnd2Y0NG9Q
SndmTmVsZ1RHZ1FLQ0FRRUE1dElacXBMbEtRTWJyRFE1ZTVkc3NyWlcKVzByNC9nQ0dDcFcxbGt3
YlY0N0lkeElUWFV6WVZ4bEc1T0RXOTBIQWowL1RadTdWdmZjOU9VZG5mMU1IMXpUQgpITWZJMDlw
ckEzbzdyb1FEdzhLL0RldVlmYTJZcnUzSkVmSzNwSGxnR0N5cmhGT0VOZjB0bUI1YVlWTlZaR2Rm
CitpSjZZSmFCRDlJU0RHVENHUEJtMFlHd1pIM1BCYUJLaDRsY29kRG50VVJKamgvd1lrbkhteENG
emo0SE1idVoKc0xpRy9IbTNyV1d5ZEdWdTU5WmR5YS9WSGc2YlRzcXlOUXBDd0xvdXRLSDNHdzc0
eDBwemJUelMzMXZoRDExSgpIWUU5dk4vbEhGYVNKSm9rRHc1dWlONC9raHNiOFI0YUJQa3FsaGZ1
R042OFJHQUZreThWeHhlS1dWVVpVZz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
"""